# Generated by Django 3.2 on 2023-11-16 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_inventorylist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_list',
            name='products',
        ),
        migrations.CreateModel(
            name='Shopping_list_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shopping_list',
            name='items',
            field=models.ManyToManyField(related_name='shopping_lists', to='main.Shopping_list_item'),
        ),
    ]
