# Generated by Django 3.2 on 2023-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20231116_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylist',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
