# Generated by Django 3.2 on 2023-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(default='1)\n2)\n3)\n4)\n5)\n'),
        ),
    ]
